package gui;

import classes.Controller;

/**
 *
 * @author miguelangel.garciar
 */
public class Console extends javax.swing.JFrame {

    Console_Thread thread;
    
    public Console(Controller controller) {
        initComponents();
        thread = new Console_Thread(controller, this);
        thread.start();
        
        
        GUIFeatures.setImageIcon(iconFuel, 40, 40, "icons/fuel");
        GUIFeatures.setImageIcon(engineIcon, engineIcon.getWidth(), engineIcon.getHeight(), "icons/engine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lab_speed = new javax.swing.JLabel();
        panelPedals = new javax.swing.JPanel();
        pb_throttle = new javax.swing.JProgressBar();
        pb_brake = new javax.swing.JProgressBar();
        pb_clutch = new javax.swing.JProgressBar();
        lab_revs = new javax.swing.JLabel();
        lab_flag = new javax.swing.JLabel();
        panelEngine = new javax.swing.JPanel();
        panelEngineValues = new javax.swing.JPanel();
        lab_damageMGUH = new javax.swing.JLabel();
        lab_damageES = new javax.swing.JLabel();
        lab_damageCE = new javax.swing.JLabel();
        lab_damageICE = new javax.swing.JLabel();
        lab_damageMGUK = new javax.swing.JLabel();
        lab_damageTC = new javax.swing.JLabel();
        lab_damageGearbox = new javax.swing.JLabel();
        engineIcon = new javax.swing.JLabel();
        panelERS = new javax.swing.JPanel();
        panelBars = new javax.swing.JPanel();
        pb_blue = new javax.swing.JProgressBar();
        pb_yellow = new javax.swing.JProgressBar();
        pb_white = new javax.swing.JProgressBar();
        panelPercentages = new javax.swing.JPanel();
        lab_ers_blue = new javax.swing.JLabel();
        lab_ers_yellow = new javax.swing.JLabel();
        lab_ers_white = new javax.swing.JLabel();
        lab_ersModeNumber = new javax.swing.JLabel();
        lab_ersDeploy = new javax.swing.JLabel();
        panelFuelMix = new javax.swing.JPanel();
        iconFuel = new javax.swing.JLabel();
        lab_fuelMix = new javax.swing.JLabel();
        panelSteer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelSteerPercentage = new javax.swing.JPanel();
        pb_steer_l = new javax.swing.JProgressBar();
        lab_steer = new javax.swing.JLabel();
        pb_steer_r = new javax.swing.JProgressBar();
        panelGlobalTyres = new javax.swing.JPanel();
        panel_tyreWearFront = new javax.swing.JPanel();
        lab_tyreWearFL = new javax.swing.JLabel();
        lab_tyreWearFR = new javax.swing.JLabel();
        panelTyres = new javax.swing.JPanel();
        pb_tyreWearFL = new javax.swing.JProgressBar();
        pb_tyreWearFR = new javax.swing.JProgressBar();
        pb_tyreWearRL = new javax.swing.JProgressBar();
        pb_tyreWearRR = new javax.swing.JProgressBar();
        panel_tyreWearFront1 = new javax.swing.JPanel();
        lab_tyreWearRL = new javax.swing.JLabel();
        lab_tyreWearRR = new javax.swing.JLabel();
        panelChecks = new javax.swing.JPanel();
        lab_pitLimiter = new javax.swing.JLabel();
        lab_drs = new javax.swing.JLabel();
        lab_abs = new javax.swing.JLabel();
        lab_gear = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lab_tyreCompound = new javax.swing.JLabel();
        panelSteer1 = new javax.swing.JPanel();
        panelSteerPercentage1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pb_revs = new javax.swing.JProgressBar();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Live Car Action");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        lab_speed.setFont(new java.awt.Font("Formula1 Display Bold", 1, 36)); // NOI18N
        lab_speed.setForeground(new java.awt.Color(255, 255, 0));
        lab_speed.setText("SPEED");

        panelPedals.setBackground(new java.awt.Color(19, 19, 19));
        panelPedals.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedals", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelPedals.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        pb_throttle.setBackground(new java.awt.Color(19, 19, 19));
        pb_throttle.setForeground(new java.awt.Color(0, 255, 0));
        pb_throttle.setOrientation(1);
        pb_throttle.setBorderPainted(false);
        panelPedals.add(pb_throttle);

        pb_brake.setBackground(new java.awt.Color(19, 19, 19));
        pb_brake.setForeground(new java.awt.Color(255, 102, 102));
        pb_brake.setOrientation(1);
        pb_brake.setBorderPainted(false);
        panelPedals.add(pb_brake);

        pb_clutch.setBackground(new java.awt.Color(19, 19, 19));
        pb_clutch.setForeground(new java.awt.Color(0, 102, 204));
        pb_clutch.setOrientation(1);
        pb_clutch.setBorderPainted(false);
        panelPedals.add(pb_clutch);

        lab_revs.setFont(new java.awt.Font("Formula1 Display Regular", 0, 12)); // NOI18N
        lab_revs.setForeground(new java.awt.Color(255, 255, 255));
        lab_revs.setText("revs.");

        lab_flag.setBackground(new java.awt.Color(19, 19, 19));
        lab_flag.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_flag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_flag.setText("FLAG");
        lab_flag.setOpaque(true);

        panelEngine.setBackground(new java.awt.Color(19, 19, 19));
        panelEngine.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Engine Damage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelEngine.setForeground(new java.awt.Color(19, 19, 19));

        panelEngineValues.setBackground(new java.awt.Color(19, 19, 19));
        panelEngineValues.setForeground(new java.awt.Color(19, 19, 19));
        panelEngineValues.setLayout(new java.awt.GridLayout(7, 0));

        lab_damageMGUH.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageMGUH.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageMGUH.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageMGUH.setText("MGU-H");
        panelEngineValues.add(lab_damageMGUH);

        lab_damageES.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageES.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageES.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageES.setText("ES");
        panelEngineValues.add(lab_damageES);

        lab_damageCE.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageCE.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageCE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageCE.setText("CE");
        panelEngineValues.add(lab_damageCE);

        lab_damageICE.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageICE.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageICE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageICE.setText("ICE");
        panelEngineValues.add(lab_damageICE);

        lab_damageMGUK.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageMGUK.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageMGUK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageMGUK.setText("MGU-K");
        panelEngineValues.add(lab_damageMGUK);

        lab_damageTC.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageTC.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageTC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageTC.setText("TC");
        panelEngineValues.add(lab_damageTC);

        lab_damageGearbox.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_damageGearbox.setForeground(new java.awt.Color(255, 255, 255));
        lab_damageGearbox.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_damageGearbox.setText("GearBox");
        panelEngineValues.add(lab_damageGearbox);

        javax.swing.GroupLayout panelEngineLayout = new javax.swing.GroupLayout(panelEngine);
        panelEngine.setLayout(panelEngineLayout);
        panelEngineLayout.setHorizontalGroup(
            panelEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEngineLayout.createSequentialGroup()
                .addComponent(panelEngineValues, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(engineIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEngineLayout.setVerticalGroup(
            panelEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(engineIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEngineValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelERS.setBackground(new java.awt.Color(19, 19, 19));
        panelERS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ERS Storage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        panelBars.setBackground(new java.awt.Color(19, 19, 19));
        panelBars.setForeground(new java.awt.Color(19, 19, 19));
        panelBars.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        pb_blue.setBackground(new java.awt.Color(51, 51, 51));
        pb_blue.setForeground(new java.awt.Color(0, 102, 255));
        panelBars.add(pb_blue);

        pb_yellow.setBackground(new java.awt.Color(51, 51, 51));
        pb_yellow.setForeground(new java.awt.Color(255, 204, 0));
        panelBars.add(pb_yellow);

        pb_white.setBackground(new java.awt.Color(51, 51, 51));
        pb_white.setForeground(new java.awt.Color(255, 255, 255));
        panelBars.add(pb_white);

        panelPercentages.setBackground(new java.awt.Color(19, 19, 19));
        panelPercentages.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        lab_ers_blue.setFont(new java.awt.Font("Formula1 Display Bold", 1, 18)); // NOI18N
        lab_ers_blue.setForeground(new java.awt.Color(0, 153, 204));
        lab_ers_blue.setText("Total");
        panelPercentages.add(lab_ers_blue);

        lab_ers_yellow.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lab_ers_yellow.setForeground(new java.awt.Color(255, 255, 0));
        lab_ers_yellow.setText("H+K");
        panelPercentages.add(lab_ers_yellow);

        lab_ers_white.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lab_ers_white.setForeground(new java.awt.Color(255, 255, 255));
        lab_ers_white.setText("Lap");
        panelPercentages.add(lab_ers_white);

        lab_ersModeNumber.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        lab_ersModeNumber.setForeground(new java.awt.Color(51, 153, 255));
        lab_ersModeNumber.setText("EL");

        lab_ersDeploy.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        lab_ersDeploy.setForeground(new java.awt.Color(51, 153, 255));
        lab_ersDeploy.setText("TBD");

        javax.swing.GroupLayout panelERSLayout = new javax.swing.GroupLayout(panelERS);
        panelERS.setLayout(panelERSLayout);
        panelERSLayout.setHorizontalGroup(
            panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelERSLayout.createSequentialGroup()
                .addComponent(panelBars, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPercentages, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelERSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_ersModeNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_ersDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelERSLayout.setVerticalGroup(
            panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelERSLayout.createSequentialGroup()
                .addGroup(panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPercentages, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_ersModeNumber)
                    .addComponent(lab_ersDeploy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFuelMix.setBackground(new java.awt.Color(19, 19, 19));
        panelFuelMix.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fuel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        iconFuel.setText("Fuel");

        lab_fuelMix.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_fuelMix.setForeground(new java.awt.Color(255, 153, 153));
        lab_fuelMix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fuelMix.setText("FuelMix");

        javax.swing.GroupLayout panelFuelMixLayout = new javax.swing.GroupLayout(panelFuelMix);
        panelFuelMix.setLayout(panelFuelMixLayout);
        panelFuelMixLayout.setHorizontalGroup(
            panelFuelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuelMixLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(iconFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_fuelMix, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelFuelMixLayout.setVerticalGroup(
            panelFuelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFuelMixLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelFuelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_fuelMix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelSteer.setBackground(new java.awt.Color(19, 19, 19));
        panelSteer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Steer angle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelSteer.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("L");
        panelSteer.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R");
        panelSteer.add(jLabel1, java.awt.BorderLayout.LINE_END);

        panelSteerPercentage.setBackground(new java.awt.Color(19, 19, 19));
        panelSteerPercentage.setLayout(new java.awt.GridLayout(1, 3));

        pb_steer_l.setBackground(new java.awt.Color(255, 255, 255));
        pb_steer_l.setForeground(new java.awt.Color(19, 19, 19));
        pb_steer_l.setValue(50);
        pb_steer_l.setBorderPainted(false);
        panelSteerPercentage.add(pb_steer_l);

        lab_steer.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_steer.setForeground(new java.awt.Color(255, 255, 255));
        lab_steer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_steer.setText("Steer %");
        panelSteerPercentage.add(lab_steer);

        pb_steer_r.setBackground(new java.awt.Color(19, 19, 19));
        pb_steer_r.setForeground(new java.awt.Color(255, 255, 255));
        pb_steer_r.setValue(50);
        panelSteerPercentage.add(pb_steer_r);

        panelSteer.add(panelSteerPercentage, java.awt.BorderLayout.CENTER);

        panelGlobalTyres.setBackground(new java.awt.Color(19, 19, 19));
        panelGlobalTyres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tyre Damage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelGlobalTyres.setLayout(new java.awt.BorderLayout());

        panel_tyreWearFront.setBackground(new java.awt.Color(19, 19, 19));
        panel_tyreWearFront.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        lab_tyreWearFL.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearFL.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearFL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearFL.setText("FL");
        panel_tyreWearFront.add(lab_tyreWearFL);

        lab_tyreWearFR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearFR.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearFR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearFR.setText("FR");
        panel_tyreWearFront.add(lab_tyreWearFR);

        panelGlobalTyres.add(panel_tyreWearFront, java.awt.BorderLayout.NORTH);

        panelTyres.setBackground(new java.awt.Color(19, 19, 19));
        panelTyres.setForeground(new java.awt.Color(19, 19, 19));
        panelTyres.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        pb_tyreWearFL.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearFL.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearFL.setOrientation(1);
        pb_tyreWearFL.setBorderPainted(false);
        panelTyres.add(pb_tyreWearFL);

        pb_tyreWearFR.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearFR.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearFR.setOrientation(1);
        pb_tyreWearFR.setBorderPainted(false);
        panelTyres.add(pb_tyreWearFR);

        pb_tyreWearRL.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearRL.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearRL.setOrientation(1);
        pb_tyreWearRL.setBorderPainted(false);
        panelTyres.add(pb_tyreWearRL);

        pb_tyreWearRR.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearRR.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearRR.setOrientation(1);
        pb_tyreWearRR.setBorderPainted(false);
        panelTyres.add(pb_tyreWearRR);

        panelGlobalTyres.add(panelTyres, java.awt.BorderLayout.CENTER);

        panel_tyreWearFront1.setBackground(new java.awt.Color(19, 19, 19));
        panel_tyreWearFront1.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        lab_tyreWearRL.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearRL.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearRL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearRL.setText("RL");
        panel_tyreWearFront1.add(lab_tyreWearRL);

        lab_tyreWearRR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearRR.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearRR.setText("RR");
        panel_tyreWearFront1.add(lab_tyreWearRR);

        panelGlobalTyres.add(panel_tyreWearFront1, java.awt.BorderLayout.SOUTH);

        panelChecks.setBackground(new java.awt.Color(19, 19, 19));
        panelChecks.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Console", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelChecks.setLayout(new java.awt.GridLayout(4, 1));

        lab_pitLimiter.setBackground(new java.awt.Color(0, 0, 0));
        lab_pitLimiter.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_pitLimiter.setForeground(new java.awt.Color(100, 100, 100));
        lab_pitLimiter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_pitLimiter.setText("PL");
        lab_pitLimiter.setOpaque(true);
        panelChecks.add(lab_pitLimiter);

        lab_drs.setBackground(new java.awt.Color(0, 0, 0));
        lab_drs.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_drs.setForeground(new java.awt.Color(255, 255, 255));
        lab_drs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_drs.setText("DRS");
        lab_drs.setOpaque(true);
        panelChecks.add(lab_drs);

        lab_abs.setBackground(new java.awt.Color(0, 0, 0));
        lab_abs.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_abs.setForeground(new java.awt.Color(255, 204, 51));
        lab_abs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_abs.setText("ABS");
        lab_abs.setOpaque(true);
        panelChecks.add(lab_abs);

        lab_gear.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_gear.setForeground(new java.awt.Color(153, 204, 255));
        lab_gear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_gear.setText("Gear");
        panelChecks.add(lab_gear);

        jPanel2.setBackground(new java.awt.Color(19, 19, 19));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compound", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        lab_tyreCompound.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        lab_tyreCompound.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreCompound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreCompound.setText("Tyre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_tyreCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_tyreCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelSteer1.setBackground(new java.awt.Color(19, 19, 19));
        panelSteer1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revs (x1000)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelSteer1.setLayout(new java.awt.BorderLayout());

        panelSteerPercentage1.setBackground(new java.awt.Color(19, 19, 19));
        panelSteerPercentage1.setLayout(new javax.swing.BoxLayout(panelSteerPercentage1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(19, 19, 19));
        jPanel3.setMaximumSize(new java.awt.Dimension(588, 15));
        jPanel3.setPreferredSize(new java.awt.Dimension(588, 15));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("3");
        jLabel2.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel3.add(jLabel2);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("6");
        jLabel3.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel3.add(jLabel3);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("9");
        jLabel7.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel3.add(jLabel7);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("12");
        jLabel8.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel3.add(jLabel8);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("15");
        jLabel9.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel3.add(jLabel9);

        panelSteerPercentage1.add(jPanel3);

        pb_revs.setBackground(new java.awt.Color(19, 19, 19));
        pb_revs.setForeground(new java.awt.Color(255, 255, 0));
        pb_revs.setMaximum(15000);
        pb_revs.setBorderPainted(false);
        panelSteerPercentage1.add(pb_revs);

        panelSteer1.add(panelSteerPercentage1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_flag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelPedals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lab_revs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelFuelMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab_speed)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(panelEngine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(panelChecks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(panelERS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(panelSteer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelGlobalTyres, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelSteer1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_flag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_revs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSteer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lab_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelSteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelChecks, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelERS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(panelEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelGlobalTyres, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFuelMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPedals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        thread.controller.removePaso(thread.paso);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel engineIcon;
    private javax.swing.JLabel iconFuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lab_abs;
    public javax.swing.JLabel lab_damageCE;
    public javax.swing.JLabel lab_damageES;
    public javax.swing.JLabel lab_damageGearbox;
    public javax.swing.JLabel lab_damageICE;
    public javax.swing.JLabel lab_damageMGUH;
    public javax.swing.JLabel lab_damageMGUK;
    public javax.swing.JLabel lab_damageTC;
    public javax.swing.JLabel lab_drs;
    public javax.swing.JLabel lab_ersDeploy;
    public javax.swing.JLabel lab_ersModeNumber;
    public javax.swing.JLabel lab_ers_blue;
    public javax.swing.JLabel lab_ers_white;
    public javax.swing.JLabel lab_ers_yellow;
    public javax.swing.JLabel lab_flag;
    public javax.swing.JLabel lab_fuelMix;
    public javax.swing.JLabel lab_gear;
    public javax.swing.JLabel lab_pitLimiter;
    public javax.swing.JLabel lab_revs;
    public javax.swing.JLabel lab_speed;
    public javax.swing.JLabel lab_steer;
    public javax.swing.JLabel lab_tyreCompound;
    public javax.swing.JLabel lab_tyreWearFL;
    public javax.swing.JLabel lab_tyreWearFR;
    public javax.swing.JLabel lab_tyreWearRL;
    public javax.swing.JLabel lab_tyreWearRR;
    private javax.swing.JPanel panelBars;
    private javax.swing.JPanel panelChecks;
    private javax.swing.JPanel panelERS;
    private javax.swing.JPanel panelEngine;
    private javax.swing.JPanel panelEngineValues;
    private javax.swing.JPanel panelFuelMix;
    private javax.swing.JPanel panelGlobalTyres;
    private javax.swing.JPanel panelPedals;
    private javax.swing.JPanel panelPercentages;
    private javax.swing.JPanel panelSteer;
    private javax.swing.JPanel panelSteer1;
    private javax.swing.JPanel panelSteerPercentage;
    private javax.swing.JPanel panelSteerPercentage1;
    private javax.swing.JPanel panelTyres;
    private javax.swing.JPanel panel_tyreWearFront;
    private javax.swing.JPanel panel_tyreWearFront1;
    public javax.swing.JProgressBar pb_blue;
    public javax.swing.JProgressBar pb_brake;
    public javax.swing.JProgressBar pb_clutch;
    public javax.swing.JProgressBar pb_revs;
    public javax.swing.JProgressBar pb_steer_l;
    public javax.swing.JProgressBar pb_steer_r;
    public javax.swing.JProgressBar pb_throttle;
    public javax.swing.JProgressBar pb_tyreWearFL;
    public javax.swing.JProgressBar pb_tyreWearFR;
    public javax.swing.JProgressBar pb_tyreWearRL;
    public javax.swing.JProgressBar pb_tyreWearRR;
    public javax.swing.JProgressBar pb_white;
    public javax.swing.JProgressBar pb_yellow;
    // End of variables declaration//GEN-END:variables
}
