package gui.carsetup;

import gui.carstatus.*;
import classes.Controller;
import classes.statics.GUIFeatures;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author miguelangel.garciar
 */
public class CarSetup extends javax.swing.JFrame {

    CarSetup_Thread thread;
    
    public CarSetup(Controller controller) {
        initComponents();
        thread = new CarSetup_Thread(controller, this);
        thread.start();
        
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for(String p : controller.session.getAllNameParticipants()){
            dcbm.addElement(p);
        }
        combo_driver.setModel(dcbm);
        
        MyItemListener actionListener = new MyItemListener(thread);
        combo_driver.addItemListener(actionListener);
        combo_driver.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelAerodynamics = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pb_fwa = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        lab_fwa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pb_rwa = new javax.swing.JProgressBar();
        jPanel24 = new javax.swing.JPanel();
        lab_rwa = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_driver = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        panelDifferential = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pb_onThrottle = new javax.swing.JProgressBar();
        jPanel25 = new javax.swing.JPanel();
        lab_onThrottle = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pb_offThrottle = new javax.swing.JProgressBar();
        jPanel26 = new javax.swing.JPanel();
        lab_offThrottle = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panelGeometry = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pb_frontCamber = new javax.swing.JProgressBar();
        jPanel42 = new javax.swing.JPanel();
        lab_frontCamber = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pb_rearCamber = new javax.swing.JProgressBar();
        jPanel41 = new javax.swing.JPanel();
        lab_rearCamber = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pb_frontToe = new javax.swing.JProgressBar();
        jPanel40 = new javax.swing.JPanel();
        lab_frontToe = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pb_rearToe = new javax.swing.JProgressBar();
        jPanel39 = new javax.swing.JPanel();
        lab_rearToe = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        panelSuspension = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pb_frontSuspension = new javax.swing.JProgressBar();
        jPanel38 = new javax.swing.JPanel();
        lab_frontSuspension = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pb_rearSuspension = new javax.swing.JProgressBar();
        jPanel37 = new javax.swing.JPanel();
        lab_rearSuspension = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pb_frontAntiRollBar = new javax.swing.JProgressBar();
        jPanel36 = new javax.swing.JPanel();
        lab_frontAntiRollBar = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pb_rearAntiRollBar = new javax.swing.JProgressBar();
        jPanel35 = new javax.swing.JPanel();
        lab_rearAntiRollBar = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pb_frontSuspensionHeight = new javax.swing.JProgressBar();
        jPanel34 = new javax.swing.JPanel();
        lab_frontRideHeight = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pb_rearSuspensionHeight = new javax.swing.JProgressBar();
        jPanel33 = new javax.swing.JPanel();
        lab_rearRideHeight = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        panelBrake = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pb_brakePressure = new javax.swing.JProgressBar();
        jPanel27 = new javax.swing.JPanel();
        lab_brakePressure = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pb_brakeBias = new javax.swing.JProgressBar();
        jPanel28 = new javax.swing.JPanel();
        lab_brakeBias = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        panelTyre = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pb_frontTyrePressure = new javax.swing.JProgressBar();
        jPanel29 = new javax.swing.JPanel();
        lab_fronTyrePressure = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        pb_rearTyrePressure = new javax.swing.JProgressBar();
        jPanel30 = new javax.swing.JPanel();
        lab_rearTyrePressure = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        panelBallast = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        pb_ballast = new javax.swing.JProgressBar();
        jPanel31 = new javax.swing.JPanel();
        lab_ballast = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panelFuel = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        pb_fuelLoad = new javax.swing.JProgressBar();
        jPanel32 = new javax.swing.JPanel();
        lab_fuelLoad = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lab_team = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Car Setup");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        jPanel4.setBackground(new java.awt.Color(19, 19, 19));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAerodynamics.setBackground(new java.awt.Color(19, 19, 19));
        panelAerodynamics.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AERODYNAMICS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelAerodynamics.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel3.setBackground(new java.awt.Color(19, 19, 19));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Front Wing Aero");
        jPanel3.add(jLabel5);

        pb_fwa.setBackground(new java.awt.Color(51, 51, 51));
        pb_fwa.setForeground(new java.awt.Color(153, 153, 153));
        pb_fwa.setMaximum(11);
        pb_fwa.setToolTipText("");
        pb_fwa.setValue(3);
        pb_fwa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_fwa.setBorderPainted(false);
        jPanel3.add(pb_fwa);

        jPanel2.setBackground(new java.awt.Color(19, 19, 19));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        lab_fwa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_fwa.setForeground(new java.awt.Color(255, 255, 255));
        lab_fwa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_fwa.setText("-");
        lab_fwa.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_fwa.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_fwa.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel2.add(lab_fwa);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Min 1 -- 11 Max");
        jPanel2.add(jLabel1);

        jPanel3.add(jPanel2);

        panelAerodynamics.add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(19, 19, 19));
        jPanel5.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Rear Wing Aero");
        jPanel5.add(jLabel7);

        pb_rwa.setBackground(new java.awt.Color(51, 51, 51));
        pb_rwa.setForeground(new java.awt.Color(153, 153, 153));
        pb_rwa.setMaximum(11);
        pb_rwa.setValue(6);
        pb_rwa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rwa.setBorderPainted(false);
        jPanel5.add(pb_rwa);

        jPanel24.setBackground(new java.awt.Color(19, 19, 19));
        jPanel24.setLayout(new java.awt.GridLayout(1, 2));

        lab_rwa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rwa.setForeground(new java.awt.Color(255, 255, 255));
        lab_rwa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rwa.setText("-");
        lab_rwa.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rwa.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rwa.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel24.add(lab_rwa);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Min 1 -- 11 Max");
        jPanel24.add(jLabel26);

        jPanel5.add(jPanel24);

        panelAerodynamics.add(jPanel5);

        jPanel4.add(panelAerodynamics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\car_setup.png")); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 460, 140));

        combo_driver.setBackground(new java.awt.Color(153, 0, 0));
        combo_driver.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        combo_driver.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(combo_driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 258, 50));

        jLabel3.setFont(new java.awt.Font("Formula1 Display Wide", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CAR SETUP");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 30));

        panelDifferential.setBackground(new java.awt.Color(19, 19, 19));
        panelDifferential.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSMISSION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelDifferential.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel6.setBackground(new java.awt.Color(19, 19, 19));
        jPanel6.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Diff. Adjustment On Throttle");
        jPanel6.add(jLabel8);

        pb_onThrottle.setBackground(new java.awt.Color(51, 51, 51));
        pb_onThrottle.setForeground(new java.awt.Color(153, 153, 153));
        pb_onThrottle.setMinimum(49);
        pb_onThrottle.setToolTipText("");
        pb_onThrottle.setValue(60);
        pb_onThrottle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_onThrottle.setBorderPainted(false);
        jPanel6.add(pb_onThrottle);

        jPanel25.setBackground(new java.awt.Color(19, 19, 19));
        jPanel25.setLayout(new java.awt.GridLayout(1, 2));

        lab_onThrottle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_onThrottle.setForeground(new java.awt.Color(255, 255, 255));
        lab_onThrottle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_onThrottle.setText("-");
        lab_onThrottle.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_onThrottle.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_onThrottle.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel25.add(lab_onThrottle);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Unlocked 50 %");
        jPanel25.add(jLabel27);

        jPanel6.add(jPanel25);

        panelDifferential.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(19, 19, 19));
        jPanel7.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Diff. Adjustment Off Throttle");
        jPanel7.add(jLabel9);

        pb_offThrottle.setBackground(new java.awt.Color(51, 51, 51));
        pb_offThrottle.setForeground(new java.awt.Color(153, 153, 153));
        pb_offThrottle.setMinimum(49);
        pb_offThrottle.setValue(60);
        pb_offThrottle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_offThrottle.setBorderPainted(false);
        jPanel7.add(pb_offThrottle);

        jPanel26.setBackground(new java.awt.Color(19, 19, 19));
        jPanel26.setLayout(new java.awt.GridLayout(1, 2));

        lab_offThrottle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_offThrottle.setForeground(new java.awt.Color(255, 255, 255));
        lab_offThrottle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_offThrottle.setText("-");
        lab_offThrottle.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_offThrottle.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_offThrottle.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel26.add(lab_offThrottle);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Locked 100 %");
        jPanel26.add(jLabel28);

        jPanel7.add(jPanel26);

        panelDifferential.add(jPanel7);

        jPanel4.add(panelDifferential, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 100));

        panelGeometry.setBackground(new java.awt.Color(19, 19, 19));
        panelGeometry.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SUSPENSION GEOMETRY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelGeometry.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel8.setBackground(new java.awt.Color(19, 19, 19));
        jPanel8.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Front Camber");
        jPanel8.add(jLabel10);

        pb_frontCamber.setBackground(new java.awt.Color(51, 51, 51));
        pb_frontCamber.setForeground(new java.awt.Color(153, 153, 153));
        pb_frontCamber.setToolTipText("");
        pb_frontCamber.setValue(60);
        pb_frontCamber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_frontCamber.setBorderPainted(false);
        jPanel8.add(pb_frontCamber);

        jPanel42.setBackground(new java.awt.Color(19, 19, 19));
        jPanel42.setLayout(new java.awt.GridLayout(1, 2));

        lab_frontCamber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_frontCamber.setForeground(new java.awt.Color(255, 255, 255));
        lab_frontCamber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_frontCamber.setText("-");
        lab_frontCamber.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_frontCamber.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_frontCamber.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel42.add(lab_frontCamber);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("-3.50 -- -2.50 º");
        jPanel42.add(jLabel44);

        jPanel8.add(jPanel42);

        panelGeometry.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(19, 19, 19));
        jPanel9.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Rear Camber");
        jPanel9.add(jLabel11);

        pb_rearCamber.setBackground(new java.awt.Color(51, 51, 51));
        pb_rearCamber.setForeground(new java.awt.Color(153, 153, 153));
        pb_rearCamber.setValue(60);
        pb_rearCamber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rearCamber.setBorderPainted(false);
        jPanel9.add(pb_rearCamber);

        jPanel41.setBackground(new java.awt.Color(19, 19, 19));
        jPanel41.setLayout(new java.awt.GridLayout(1, 2));

        lab_rearCamber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rearCamber.setForeground(new java.awt.Color(255, 255, 255));
        lab_rearCamber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rearCamber.setText("-");
        lab_rearCamber.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rearCamber.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rearCamber.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel41.add(lab_rearCamber);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("-2.00 -- -1.00 º");
        jPanel41.add(jLabel43);

        jPanel9.add(jPanel41);

        panelGeometry.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(19, 19, 19));
        jPanel10.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel10.setLayout(new java.awt.GridLayout(1, 3));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Front Toe");
        jPanel10.add(jLabel12);

        pb_frontToe.setBackground(new java.awt.Color(51, 51, 51));
        pb_frontToe.setForeground(new java.awt.Color(153, 153, 153));
        pb_frontToe.setMaximum(10);
        pb_frontToe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_frontToe.setBorderPainted(false);
        jPanel10.add(pb_frontToe);

        jPanel40.setBackground(new java.awt.Color(19, 19, 19));
        jPanel40.setLayout(new java.awt.GridLayout(1, 2));

        lab_frontToe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_frontToe.setForeground(new java.awt.Color(255, 255, 255));
        lab_frontToe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_frontToe.setText("-");
        lab_frontToe.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_frontToe.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_frontToe.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel40.add(lab_frontToe);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("0.05 --  0.15 º");
        jPanel40.add(jLabel42);

        jPanel10.add(jPanel40);

        panelGeometry.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(19, 19, 19));
        jPanel11.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel11.setLayout(new java.awt.GridLayout(1, 3));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Rear Toe");
        jPanel11.add(jLabel13);

        pb_rearToe.setBackground(new java.awt.Color(51, 51, 51));
        pb_rearToe.setForeground(new java.awt.Color(153, 153, 153));
        pb_rearToe.setMaximum(50);
        pb_rearToe.setMinimum(20);
        pb_rearToe.setValue(30);
        pb_rearToe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rearToe.setBorderPainted(false);
        jPanel11.add(pb_rearToe);

        jPanel39.setBackground(new java.awt.Color(19, 19, 19));
        jPanel39.setLayout(new java.awt.GridLayout(1, 2));

        lab_rearToe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rearToe.setForeground(new java.awt.Color(255, 255, 255));
        lab_rearToe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rearToe.setText("-");
        lab_rearToe.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rearToe.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rearToe.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel39.add(lab_rearToe);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("0.20 --  0.50 º");
        jPanel39.add(jLabel41);

        jPanel11.add(jPanel39);

        panelGeometry.add(jPanel11);

        jPanel4.add(panelGeometry, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 600, 170));

        panelSuspension.setBackground(new java.awt.Color(19, 19, 19));
        panelSuspension.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SUSPENSION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelSuspension.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel12.setBackground(new java.awt.Color(19, 19, 19));
        jPanel12.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel12.setLayout(new java.awt.GridLayout(1, 3));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Front Suspension");
        jPanel12.add(jLabel14);

        pb_frontSuspension.setBackground(new java.awt.Color(51, 51, 51));
        pb_frontSuspension.setForeground(new java.awt.Color(153, 153, 153));
        pb_frontSuspension.setMaximum(11);
        pb_frontSuspension.setToolTipText("");
        pb_frontSuspension.setValue(3);
        pb_frontSuspension.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_frontSuspension.setBorderPainted(false);
        jPanel12.add(pb_frontSuspension);

        jPanel38.setBackground(new java.awt.Color(19, 19, 19));
        jPanel38.setLayout(new java.awt.GridLayout(1, 2));

        lab_frontSuspension.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_frontSuspension.setForeground(new java.awt.Color(255, 255, 255));
        lab_frontSuspension.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_frontSuspension.setText("-");
        lab_frontSuspension.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_frontSuspension.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_frontSuspension.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel38.add(lab_frontSuspension);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Soft 1 -- 11 Firm");
        jPanel38.add(jLabel40);

        jPanel12.add(jPanel38);

        panelSuspension.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(19, 19, 19));
        jPanel13.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel13.setLayout(new java.awt.GridLayout(1, 3));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Rear Suspension");
        jPanel13.add(jLabel15);

        pb_rearSuspension.setBackground(new java.awt.Color(51, 51, 51));
        pb_rearSuspension.setForeground(new java.awt.Color(153, 153, 153));
        pb_rearSuspension.setMaximum(11);
        pb_rearSuspension.setValue(3);
        pb_rearSuspension.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rearSuspension.setBorderPainted(false);
        jPanel13.add(pb_rearSuspension);

        jPanel37.setBackground(new java.awt.Color(19, 19, 19));
        jPanel37.setLayout(new java.awt.GridLayout(1, 2));

        lab_rearSuspension.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rearSuspension.setForeground(new java.awt.Color(255, 255, 255));
        lab_rearSuspension.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rearSuspension.setText("-");
        lab_rearSuspension.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rearSuspension.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rearSuspension.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel37.add(lab_rearSuspension);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Soft 1 -- 11 Firm");
        jPanel37.add(jLabel39);

        jPanel13.add(jPanel37);

        panelSuspension.add(jPanel13);

        jPanel16.setBackground(new java.awt.Color(19, 19, 19));
        jPanel16.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel16.setLayout(new java.awt.GridLayout(1, 3));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Front Anti-Roll Bar");
        jPanel16.add(jLabel18);

        pb_frontAntiRollBar.setBackground(new java.awt.Color(51, 51, 51));
        pb_frontAntiRollBar.setForeground(new java.awt.Color(153, 153, 153));
        pb_frontAntiRollBar.setMaximum(11);
        pb_frontAntiRollBar.setValue(3);
        pb_frontAntiRollBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_frontAntiRollBar.setBorderPainted(false);
        jPanel16.add(pb_frontAntiRollBar);

        jPanel36.setBackground(new java.awt.Color(19, 19, 19));
        jPanel36.setLayout(new java.awt.GridLayout(1, 2));

        lab_frontAntiRollBar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_frontAntiRollBar.setForeground(new java.awt.Color(255, 255, 255));
        lab_frontAntiRollBar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_frontAntiRollBar.setText("-");
        lab_frontAntiRollBar.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_frontAntiRollBar.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_frontAntiRollBar.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel36.add(lab_frontAntiRollBar);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Soft 1 -- 11 Firm");
        jPanel36.add(jLabel38);

        jPanel16.add(jPanel36);

        panelSuspension.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(19, 19, 19));
        jPanel17.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel17.setLayout(new java.awt.GridLayout(1, 3));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Rear Anti-Roll Bar");
        jPanel17.add(jLabel19);

        pb_rearAntiRollBar.setBackground(new java.awt.Color(51, 51, 51));
        pb_rearAntiRollBar.setForeground(new java.awt.Color(153, 153, 153));
        pb_rearAntiRollBar.setMaximum(11);
        pb_rearAntiRollBar.setValue(3);
        pb_rearAntiRollBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rearAntiRollBar.setBorderPainted(false);
        jPanel17.add(pb_rearAntiRollBar);

        jPanel35.setBackground(new java.awt.Color(19, 19, 19));
        jPanel35.setLayout(new java.awt.GridLayout(1, 2));

        lab_rearAntiRollBar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rearAntiRollBar.setForeground(new java.awt.Color(255, 255, 255));
        lab_rearAntiRollBar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rearAntiRollBar.setText("-");
        lab_rearAntiRollBar.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rearAntiRollBar.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rearAntiRollBar.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel35.add(lab_rearAntiRollBar);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Soft 1 -- 11 Firm");
        jPanel35.add(jLabel37);

        jPanel17.add(jPanel35);

        panelSuspension.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(19, 19, 19));
        jPanel18.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel18.setLayout(new java.awt.GridLayout(1, 3));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Front Ride Height");
        jPanel18.add(jLabel20);

        pb_frontSuspensionHeight.setBackground(new java.awt.Color(51, 51, 51));
        pb_frontSuspensionHeight.setForeground(new java.awt.Color(153, 153, 153));
        pb_frontSuspensionHeight.setMaximum(11);
        pb_frontSuspensionHeight.setValue(3);
        pb_frontSuspensionHeight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_frontSuspensionHeight.setBorderPainted(false);
        jPanel18.add(pb_frontSuspensionHeight);

        jPanel34.setBackground(new java.awt.Color(19, 19, 19));
        jPanel34.setLayout(new java.awt.GridLayout(1, 2));

        lab_frontRideHeight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_frontRideHeight.setForeground(new java.awt.Color(255, 255, 255));
        lab_frontRideHeight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_frontRideHeight.setText("-");
        lab_frontRideHeight.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_frontRideHeight.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_frontRideHeight.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel34.add(lab_frontRideHeight);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Min 1 -- 11 Max");
        jPanel34.add(jLabel36);

        jPanel18.add(jPanel34);

        panelSuspension.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(19, 19, 19));
        jPanel19.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel19.setLayout(new java.awt.GridLayout(1, 3));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Rear Ride Height");
        jPanel19.add(jLabel21);

        pb_rearSuspensionHeight.setBackground(new java.awt.Color(51, 51, 51));
        pb_rearSuspensionHeight.setForeground(new java.awt.Color(153, 153, 153));
        pb_rearSuspensionHeight.setMaximum(11);
        pb_rearSuspensionHeight.setValue(3);
        pb_rearSuspensionHeight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rearSuspensionHeight.setBorderPainted(false);
        jPanel19.add(pb_rearSuspensionHeight);

        jPanel33.setBackground(new java.awt.Color(19, 19, 19));
        jPanel33.setLayout(new java.awt.GridLayout(1, 2));

        lab_rearRideHeight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rearRideHeight.setForeground(new java.awt.Color(255, 255, 255));
        lab_rearRideHeight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rearRideHeight.setText("-");
        lab_rearRideHeight.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rearRideHeight.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rearRideHeight.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel33.add(lab_rearRideHeight);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Min 1 -- 11 Max");
        jPanel33.add(jLabel35);

        jPanel19.add(jPanel33);

        panelSuspension.add(jPanel19);

        jPanel4.add(panelSuspension, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 600, 230));

        panelBrake.setBackground(new java.awt.Color(19, 19, 19));
        panelBrake.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BRAKES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelBrake.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel14.setBackground(new java.awt.Color(19, 19, 19));
        jPanel14.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel14.setLayout(new java.awt.GridLayout(1, 3));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Brake Pressure");
        jPanel14.add(jLabel16);

        pb_brakePressure.setBackground(new java.awt.Color(51, 51, 51));
        pb_brakePressure.setForeground(new java.awt.Color(153, 153, 153));
        pb_brakePressure.setMinimum(50);
        pb_brakePressure.setToolTipText("");
        pb_brakePressure.setValue(60);
        pb_brakePressure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_brakePressure.setBorderPainted(false);
        jPanel14.add(pb_brakePressure);

        jPanel27.setBackground(new java.awt.Color(19, 19, 19));
        jPanel27.setLayout(new java.awt.GridLayout(1, 2));

        lab_brakePressure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_brakePressure.setForeground(new java.awt.Color(255, 255, 255));
        lab_brakePressure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_brakePressure.setText("-");
        lab_brakePressure.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_brakePressure.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_brakePressure.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel27.add(lab_brakePressure);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Min 50 -- 100 %");
        jPanel27.add(jLabel29);

        jPanel14.add(jPanel27);

        panelBrake.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(19, 19, 19));
        jPanel15.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel15.setLayout(new java.awt.GridLayout(1, 3));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Front Brake Bias");
        jPanel15.add(jLabel17);

        pb_brakeBias.setBackground(new java.awt.Color(51, 51, 51));
        pb_brakeBias.setForeground(new java.awt.Color(153, 153, 153));
        pb_brakeBias.setMaximum(20);
        pb_brakeBias.setValue(5);
        pb_brakeBias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_brakeBias.setBorderPainted(false);
        jPanel15.add(pb_brakeBias);

        jPanel28.setBackground(new java.awt.Color(19, 19, 19));
        jPanel28.setLayout(new java.awt.GridLayout(1, 2));

        lab_brakeBias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_brakeBias.setForeground(new java.awt.Color(255, 255, 255));
        lab_brakeBias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_brakeBias.setText("-");
        lab_brakeBias.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_brakeBias.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_brakeBias.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel28.add(lab_brakeBias);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Fr 70 -- 50% Re");
        jPanel28.add(jLabel30);

        jPanel15.add(jPanel28);

        panelBrake.add(jPanel15);

        jPanel4.add(panelBrake, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 600, 100));

        panelTyre.setBackground(new java.awt.Color(19, 19, 19));
        panelTyre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TYRES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelTyre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel20.setBackground(new java.awt.Color(19, 19, 19));
        jPanel20.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel20.setLayout(new java.awt.GridLayout(1, 3));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Front Tyre Pressure");
        jPanel20.add(jLabel22);

        pb_frontTyrePressure.setBackground(new java.awt.Color(51, 51, 51));
        pb_frontTyrePressure.setForeground(new java.awt.Color(153, 153, 153));
        pb_frontTyrePressure.setMaximum(250);
        pb_frontTyrePressure.setMinimum(210);
        pb_frontTyrePressure.setToolTipText("");
        pb_frontTyrePressure.setValue(225);
        pb_frontTyrePressure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_frontTyrePressure.setBorderPainted(false);
        jPanel20.add(pb_frontTyrePressure);

        jPanel29.setBackground(new java.awt.Color(19, 19, 19));
        jPanel29.setLayout(new java.awt.GridLayout(1, 2));

        lab_fronTyrePressure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_fronTyrePressure.setForeground(new java.awt.Color(255, 255, 255));
        lab_fronTyrePressure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_fronTyrePressure.setText("-");
        lab_fronTyrePressure.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_fronTyrePressure.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_fronTyrePressure.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel29.add(lab_fronTyrePressure);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("21.0 -- 25.0 PSI");
        jPanel29.add(jLabel31);

        jPanel20.add(jPanel29);

        panelTyre.add(jPanel20);

        jPanel21.setBackground(new java.awt.Color(19, 19, 19));
        jPanel21.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel21.setLayout(new java.awt.GridLayout(1, 3));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Rear Tyre Pressure");
        jPanel21.add(jLabel23);

        pb_rearTyrePressure.setBackground(new java.awt.Color(51, 51, 51));
        pb_rearTyrePressure.setForeground(new java.awt.Color(153, 153, 153));
        pb_rearTyrePressure.setMaximum(235);
        pb_rearTyrePressure.setMinimum(195);
        pb_rearTyrePressure.setValue(210);
        pb_rearTyrePressure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_rearTyrePressure.setBorderPainted(false);
        jPanel21.add(pb_rearTyrePressure);

        jPanel30.setBackground(new java.awt.Color(19, 19, 19));
        jPanel30.setLayout(new java.awt.GridLayout(1, 2));

        lab_rearTyrePressure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_rearTyrePressure.setForeground(new java.awt.Color(255, 255, 255));
        lab_rearTyrePressure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_rearTyrePressure.setText("-");
        lab_rearTyrePressure.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rearTyrePressure.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rearTyrePressure.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel30.add(lab_rearTyrePressure);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("19.5 -- 23.5 PSI");
        jPanel30.add(jLabel32);

        jPanel21.add(jPanel30);

        panelTyre.add(jPanel21);

        jPanel4.add(panelTyre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 600, 100));

        panelBallast.setBackground(new java.awt.Color(19, 19, 19));
        panelBallast.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WEIGHT DISTRIBUTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelBallast.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel22.setBackground(new java.awt.Color(19, 19, 19));
        jPanel22.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel22.setLayout(new java.awt.GridLayout(1, 3));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Ballast");
        jPanel22.add(jLabel24);

        pb_ballast.setBackground(new java.awt.Color(51, 51, 51));
        pb_ballast.setForeground(new java.awt.Color(153, 153, 153));
        pb_ballast.setMaximum(11);
        pb_ballast.setToolTipText("");
        pb_ballast.setValue(5);
        pb_ballast.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_ballast.setBorderPainted(false);
        jPanel22.add(pb_ballast);

        jPanel31.setBackground(new java.awt.Color(19, 19, 19));
        jPanel31.setLayout(new java.awt.GridLayout(1, 2));

        lab_ballast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_ballast.setForeground(new java.awt.Color(255, 255, 255));
        lab_ballast.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_ballast.setText("-");
        lab_ballast.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_ballast.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_ballast.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel31.add(lab_ballast);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Fr 1 -- 11 Re");
        jPanel31.add(jLabel33);

        jPanel22.add(jPanel31);

        panelBallast.add(jPanel22);

        jPanel4.add(panelBallast, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 600, 70));

        panelFuel.setBackground(new java.awt.Color(19, 19, 19));
        panelFuel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUEL LOAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelFuel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jPanel23.setBackground(new java.awt.Color(19, 19, 19));
        jPanel23.setPreferredSize(new java.awt.Dimension(550, 25));
        jPanel23.setLayout(new java.awt.GridLayout(1, 3));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Fuel Load");
        jPanel23.add(jLabel25);

        pb_fuelLoad.setBackground(new java.awt.Color(51, 51, 51));
        pb_fuelLoad.setForeground(new java.awt.Color(153, 153, 153));
        pb_fuelLoad.setMaximum(105);
        pb_fuelLoad.setToolTipText("");
        pb_fuelLoad.setValue(60);
        pb_fuelLoad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 5, true));
        pb_fuelLoad.setBorderPainted(false);
        jPanel23.add(pb_fuelLoad);

        jPanel32.setBackground(new java.awt.Color(19, 19, 19));
        jPanel32.setLayout(new java.awt.GridLayout(1, 2));

        lab_fuelLoad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_fuelLoad.setForeground(new java.awt.Color(255, 255, 255));
        lab_fuelLoad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lab_fuelLoad.setText("-");
        lab_fuelLoad.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_fuelLoad.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_fuelLoad.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel32.add(lab_fuelLoad);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("5 -- 105 kg");
        jPanel32.add(jLabel34);

        jPanel23.add(jPanel32);

        panelFuel.add(jPanel23);

        jPanel4.add(panelFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 600, 70));

        lab_team.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_team.setForeground(new java.awt.Color(255, 51, 51));
        lab_team.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_team.setText("FERRARI");
        jPanel4.add(lab_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 470, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        thread.controller.removePaso(thread.paso);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> combo_driver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lab_ballast;
    public javax.swing.JLabel lab_brakeBias;
    public javax.swing.JLabel lab_brakePressure;
    public javax.swing.JLabel lab_fronTyrePressure;
    public javax.swing.JLabel lab_frontAntiRollBar;
    public javax.swing.JLabel lab_frontCamber;
    public javax.swing.JLabel lab_frontRideHeight;
    public javax.swing.JLabel lab_frontSuspension;
    public javax.swing.JLabel lab_frontToe;
    public javax.swing.JLabel lab_fuelLoad;
    public javax.swing.JLabel lab_fwa;
    public javax.swing.JLabel lab_offThrottle;
    public javax.swing.JLabel lab_onThrottle;
    public javax.swing.JLabel lab_rearAntiRollBar;
    public javax.swing.JLabel lab_rearCamber;
    public javax.swing.JLabel lab_rearRideHeight;
    public javax.swing.JLabel lab_rearSuspension;
    public javax.swing.JLabel lab_rearToe;
    public javax.swing.JLabel lab_rearTyrePressure;
    public javax.swing.JLabel lab_rwa;
    public javax.swing.JLabel lab_team;
    private javax.swing.JPanel panelAerodynamics;
    private javax.swing.JPanel panelBallast;
    private javax.swing.JPanel panelBrake;
    private javax.swing.JPanel panelDifferential;
    private javax.swing.JPanel panelFuel;
    private javax.swing.JPanel panelGeometry;
    private javax.swing.JPanel panelSuspension;
    private javax.swing.JPanel panelTyre;
    public javax.swing.JProgressBar pb_ballast;
    public javax.swing.JProgressBar pb_brakeBias;
    public javax.swing.JProgressBar pb_brakePressure;
    public javax.swing.JProgressBar pb_frontAntiRollBar;
    public javax.swing.JProgressBar pb_frontCamber;
    public javax.swing.JProgressBar pb_frontSuspension;
    public javax.swing.JProgressBar pb_frontSuspensionHeight;
    public javax.swing.JProgressBar pb_frontToe;
    public javax.swing.JProgressBar pb_frontTyrePressure;
    public javax.swing.JProgressBar pb_fuelLoad;
    public javax.swing.JProgressBar pb_fwa;
    public javax.swing.JProgressBar pb_offThrottle;
    public javax.swing.JProgressBar pb_onThrottle;
    public javax.swing.JProgressBar pb_rearAntiRollBar;
    public javax.swing.JProgressBar pb_rearCamber;
    public javax.swing.JProgressBar pb_rearSuspension;
    public javax.swing.JProgressBar pb_rearSuspensionHeight;
    public javax.swing.JProgressBar pb_rearToe;
    public javax.swing.JProgressBar pb_rearTyrePressure;
    public javax.swing.JProgressBar pb_rwa;
    // End of variables declaration//GEN-END:variables
}

class MyItemListener implements ItemListener {

    CarSetup_Thread thread;
    
    public MyItemListener(CarSetup_Thread t){
        thread = t;
    }
    
    public void itemStateChanged(ItemEvent evt) {
        JComboBox cb = (JComboBox) evt.getSource();

        String item = (String) evt.getItem();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            thread.setDriver(thread.controller.session.getDriverByName(item));
        }
        
        thread.paso.abrir();
    }
}