package gui.carstatus;

import classes.Controller;
import classes.statics.GUIFeatures;
import classes.statics.ProgressCircleUI;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.plaf.ProgressBarUI;
import java.awt.*;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author miguelangel.garciar
 */
public class CarStatus extends javax.swing.JFrame {

    CarStatus_Thread thread;
    
    public CarStatus(Controller controller) {
        initComponents();
        thread = new CarStatus_Thread(controller, this);
        thread.start();
        
        
        ArrayList<String> driversNames = controller.session.getAllNameParticipants();
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for(String p : driversNames){
            dcbm.addElement(p);
        }
        combo_driver.setModel(dcbm);
        
        MyItemListener actionListener = new MyItemListener(thread);
        combo_driver.addItemListener(actionListener);
        combo_driver.setSelectedIndex(-1);
        
        GUIFeatures.setImageIcon(iconFuel, 40, 40, "icons/fuel");
        
        ProgressCircleUI.initialize(pb_tyreWearFL);
        ProgressCircleUI.initialize(pb_tyreWearFR);
        ProgressCircleUI.initialize(pb_tyreWearRL);
        ProgressCircleUI.initialize(pb_tyreWearRR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lab_flag = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelChecks = new javax.swing.JPanel();
        lab_pitLimiter = new javax.swing.JLabel();
        lab_drs = new javax.swing.JLabel();
        lab_abs = new javax.swing.JLabel();
        lab_gear = new javax.swing.JLabel();
        panelFuelMix = new javax.swing.JPanel();
        iconFuel = new javax.swing.JLabel();
        lab_fuelMix = new javax.swing.JLabel();
        pb_fuel = new javax.swing.JProgressBar();
        lab_fuelExcess = new javax.swing.JLabel();
        lab_fuelInTank = new javax.swing.JLabel();
        panelERS = new javax.swing.JPanel();
        panelBars = new javax.swing.JPanel();
        pb_blue = new javax.swing.JProgressBar();
        pb_yellow = new javax.swing.JProgressBar();
        pb_white = new javax.swing.JProgressBar();
        panelPercentages = new javax.swing.JPanel();
        lab_ers_blue = new javax.swing.JLabel();
        lab_ers_yellow = new javax.swing.JLabel();
        lab_ers_white = new javax.swing.JLabel();
        lab_ersModeNumber = new javax.swing.JLabel();
        lab_ersDeploy = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        carDamageIcon = new javax.swing.JLabel();
        pb_tyreWearRR = new javax.swing.JProgressBar();
        pb_tyreWearRL = new javax.swing.JProgressBar();
        lab_FRWD = new javax.swing.JLabel();
        pb_tyreWearFL = new javax.swing.JProgressBar();
        pb_frwd = new javax.swing.JProgressBar();
        pb_rwd = new javax.swing.JProgressBar();
        lab_rwd = new javax.swing.JLabel();
        pb_flwd = new javax.swing.JProgressBar();
        lab_FLWD = new javax.swing.JLabel();
        pb_tyreWearFR = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lab_engine_damage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lab_exhaust_damage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lab_gearbox_damage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lab_engine_temp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lab_tyreCompound = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lab_brakeTempFL = new javax.swing.JLabel();
        lab_brakeTempFR = new javax.swing.JLabel();
        lab_brakeTempRL = new javax.swing.JLabel();
        lab_brakeTempRR = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lab_tyreSurfaceTempFL = new javax.swing.JLabel();
        lab_tyreSurfaceTempFR = new javax.swing.JLabel();
        lab_tyreSurfaceTempRL = new javax.swing.JLabel();
        lab_tyreSurfaceTempRR = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lab_tyreInnerTempFL = new javax.swing.JLabel();
        lab_tyreInnerTempFR = new javax.swing.JLabel();
        lab_tyreInnerTempRL = new javax.swing.JLabel();
        lab_tyreInnerTempRR = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lab_tyrePressureFL = new javax.swing.JLabel();
        lab_tyrePressureFR = new javax.swing.JLabel();
        lab_tyrePressureRL = new javax.swing.JLabel();
        lab_tyrePressureRR = new javax.swing.JLabel();
        panelPedals = new javax.swing.JPanel();
        pb_throttle = new javax.swing.JProgressBar();
        pb_brake = new javax.swing.JProgressBar();
        pb_clutch = new javax.swing.JProgressBar();
        lab_revs = new javax.swing.JLabel();
        panelSteer1 = new javax.swing.JPanel();
        panelSteerPercentage1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lab_revLight1 = new javax.swing.JLabel();
        lab_revLight2 = new javax.swing.JLabel();
        lab_revLight3 = new javax.swing.JLabel();
        lab_revLight4 = new javax.swing.JLabel();
        lab_revLight5 = new javax.swing.JLabel();
        lab_revLight6 = new javax.swing.JLabel();
        lab_revLight7 = new javax.swing.JLabel();
        lab_revLight8 = new javax.swing.JLabel();
        lab_revLight9 = new javax.swing.JLabel();
        lab_revLight10 = new javax.swing.JLabel();
        lab_revLight11 = new javax.swing.JLabel();
        lab_revLight12 = new javax.swing.JLabel();
        lab_revLight13 = new javax.swing.JLabel();
        lab_revLight14 = new javax.swing.JLabel();
        lab_revLight15 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pb_revs = new javax.swing.JProgressBar();
        panelSteer = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelSteerPercentage = new javax.swing.JPanel();
        pb_steer_l = new javax.swing.JProgressBar();
        lab_steer = new javax.swing.JLabel();
        pb_steer_r = new javax.swing.JProgressBar();
        combo_driver = new javax.swing.JComboBox<>();
        lab_speed = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Live Car Action");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        lab_flag.setBackground(new java.awt.Color(19, 19, 19));
        lab_flag.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_flag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_flag.setText("FLAG");
        lab_flag.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(19, 19, 19));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelChecks.setBackground(new java.awt.Color(19, 19, 19));
        panelChecks.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Console", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelChecks.setLayout(new java.awt.GridLayout(4, 1));

        lab_pitLimiter.setBackground(new java.awt.Color(0, 0, 0));
        lab_pitLimiter.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_pitLimiter.setForeground(new java.awt.Color(100, 100, 100));
        lab_pitLimiter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_pitLimiter.setText("PL");
        lab_pitLimiter.setOpaque(true);
        panelChecks.add(lab_pitLimiter);

        lab_drs.setBackground(new java.awt.Color(0, 0, 0));
        lab_drs.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_drs.setForeground(new java.awt.Color(255, 255, 255));
        lab_drs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_drs.setText("DRS");
        lab_drs.setOpaque(true);
        panelChecks.add(lab_drs);

        lab_abs.setBackground(new java.awt.Color(0, 0, 0));
        lab_abs.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_abs.setForeground(new java.awt.Color(255, 204, 51));
        lab_abs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_abs.setText("ABS");
        lab_abs.setOpaque(true);
        panelChecks.add(lab_abs);

        lab_gear.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_gear.setForeground(new java.awt.Color(153, 204, 255));
        lab_gear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_gear.setText("Gear");
        panelChecks.add(lab_gear);

        jPanel4.add(panelChecks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 160));

        panelFuelMix.setBackground(new java.awt.Color(19, 19, 19));
        panelFuelMix.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fuel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelFuelMix.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconFuel.setText("Fuel");
        panelFuelMix.add(iconFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        lab_fuelMix.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_fuelMix.setForeground(new java.awt.Color(255, 153, 153));
        lab_fuelMix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fuelMix.setText("FuelMix");
        panelFuelMix.add(lab_fuelMix, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 129, 40));

        pb_fuel.setBackground(new java.awt.Color(0, 0, 0));
        pb_fuel.setForeground(new java.awt.Color(0, 204, 153));
        pb_fuel.setBorderPainted(false);
        panelFuelMix.add(pb_fuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 760, -1));

        lab_fuelExcess.setFont(new java.awt.Font("Formula1 Display Bold", 1, 18)); // NOI18N
        lab_fuelExcess.setForeground(new java.awt.Color(0, 153, 204));
        lab_fuelExcess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fuelExcess.setText("Total");
        panelFuelMix.add(lab_fuelExcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 80, 50));

        lab_fuelInTank.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_fuelInTank.setForeground(new java.awt.Color(102, 102, 102));
        lab_fuelInTank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fuelInTank.setText("FuelMix");
        panelFuelMix.add(lab_fuelInTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 129, 40));

        jPanel4.add(panelFuelMix, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 880, 90));

        panelERS.setBackground(new java.awt.Color(19, 19, 19));
        panelERS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ERS Storage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        panelBars.setBackground(new java.awt.Color(19, 19, 19));
        panelBars.setForeground(new java.awt.Color(19, 19, 19));
        panelBars.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        pb_blue.setBackground(new java.awt.Color(51, 51, 51));
        pb_blue.setForeground(new java.awt.Color(0, 102, 255));
        pb_blue.setBorderPainted(false);
        panelBars.add(pb_blue);

        pb_yellow.setBackground(new java.awt.Color(51, 51, 51));
        pb_yellow.setForeground(new java.awt.Color(255, 204, 0));
        pb_yellow.setBorderPainted(false);
        panelBars.add(pb_yellow);

        pb_white.setBackground(new java.awt.Color(51, 51, 51));
        pb_white.setForeground(new java.awt.Color(255, 255, 255));
        pb_white.setBorderPainted(false);
        panelBars.add(pb_white);

        panelPercentages.setBackground(new java.awt.Color(19, 19, 19));
        panelPercentages.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        lab_ers_blue.setFont(new java.awt.Font("Formula1 Display Bold", 1, 18)); // NOI18N
        lab_ers_blue.setForeground(new java.awt.Color(0, 153, 204));
        lab_ers_blue.setText("Total");
        panelPercentages.add(lab_ers_blue);

        lab_ers_yellow.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lab_ers_yellow.setForeground(new java.awt.Color(255, 255, 0));
        lab_ers_yellow.setText("H+K");
        panelPercentages.add(lab_ers_yellow);

        lab_ers_white.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lab_ers_white.setForeground(new java.awt.Color(255, 255, 255));
        lab_ers_white.setText("Lap");
        panelPercentages.add(lab_ers_white);

        lab_ersModeNumber.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        lab_ersModeNumber.setForeground(new java.awt.Color(51, 153, 255));
        lab_ersModeNumber.setText("EL");

        lab_ersDeploy.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        lab_ersDeploy.setForeground(new java.awt.Color(51, 153, 255));
        lab_ersDeploy.setText("TBD");

        javax.swing.GroupLayout panelERSLayout = new javax.swing.GroupLayout(panelERS);
        panelERS.setLayout(panelERSLayout);
        panelERSLayout.setHorizontalGroup(
            panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelERSLayout.createSequentialGroup()
                .addComponent(panelBars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPercentages, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelERSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_ersModeNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_ersDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelERSLayout.setVerticalGroup(
            panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelERSLayout.createSequentialGroup()
                .addGroup(panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPercentages, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_ersModeNumber)
                    .addComponent(lab_ersDeploy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(panelERS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 580, -1));

        jPanel3.setBackground(new java.awt.Color(19, 19, 19));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Damage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carDamageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carDamageIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\car_damage.png")); // NOI18N
        jPanel3.add(carDamageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 170));

        pb_tyreWearRR.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearRR.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearRR.setBorderPainted(false);
        jPanel3.add(pb_tyreWearRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 80));

        pb_tyreWearRL.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearRL.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearRL.setBorderPainted(false);
        jPanel3.add(pb_tyreWearRL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 80));

        lab_FRWD.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_FRWD.setForeground(new java.awt.Color(153, 204, 255));
        lab_FRWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_FRWD.setText("FWR");
        lab_FRWD.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_FRWD.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_FRWD.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_FRWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 20));

        pb_tyreWearFL.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearFL.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearFL.setBorderPainted(false);
        jPanel3.add(pb_tyreWearFL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 80));

        pb_frwd.setBackground(new java.awt.Color(51, 51, 51));
        pb_frwd.setForeground(new java.awt.Color(0, 255, 0));
        pb_frwd.setValue(50);
        pb_frwd.setBorderPainted(false);
        jPanel3.add(pb_frwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, -1));

        pb_rwd.setBackground(new java.awt.Color(51, 51, 51));
        pb_rwd.setForeground(new java.awt.Color(0, 255, 0));
        pb_rwd.setValue(50);
        pb_rwd.setBorderPainted(false);
        jPanel3.add(pb_rwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, -1));

        lab_rwd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_rwd.setForeground(new java.awt.Color(153, 204, 255));
        lab_rwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_rwd.setText("RW");
        lab_rwd.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rwd.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rwd.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_rwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 260, 20));

        pb_flwd.setBackground(new java.awt.Color(51, 51, 51));
        pb_flwd.setForeground(new java.awt.Color(0, 255, 0));
        pb_flwd.setValue(50);
        pb_flwd.setBorderPainted(false);
        jPanel3.add(pb_flwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        lab_FLWD.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_FLWD.setForeground(new java.awt.Color(153, 204, 255));
        lab_FLWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_FLWD.setText("FWL");
        lab_FLWD.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_FLWD.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_FLWD.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_FLWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 20));

        pb_tyreWearFR.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearFR.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearFR.setBorderPainted(false);
        jPanel3.add(pb_tyreWearFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 80, 80));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 290, 300));

        jPanel5.setBackground(new java.awt.Color(19, 19, 19));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Engine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Engine");
        jPanel5.add(jLabel1);

        lab_engine_damage.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_engine_damage.setForeground(new java.awt.Color(255, 255, 0));
        lab_engine_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_engine_damage.setText("jLabel2");
        jPanel5.add(lab_engine_damage);

        jLabel3.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Exhaust");
        jPanel5.add(jLabel3);

        lab_exhaust_damage.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_exhaust_damage.setForeground(new java.awt.Color(255, 255, 0));
        lab_exhaust_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_exhaust_damage.setText("jLabel2");
        jPanel5.add(lab_exhaust_damage);

        jLabel7.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gear Box");
        jPanel5.add(jLabel7);

        lab_gearbox_damage.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_gearbox_damage.setForeground(new java.awt.Color(255, 255, 0));
        lab_gearbox_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_gearbox_damage.setText("jLabel2");
        jPanel5.add(lab_gearbox_damage);

        jLabel11.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Engine Temp.");
        jPanel5.add(jLabel11);

        lab_engine_temp.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_engine_temp.setForeground(new java.awt.Color(255, 255, 0));
        lab_engine_temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_engine_temp.setText("jLabel2");
        jPanel5.add(lab_engine_temp);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 340, 110));

        jPanel2.setBackground(new java.awt.Color(19, 19, 19));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compound", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        lab_tyreCompound.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        lab_tyreCompound.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreCompound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreCompound.setText("Tyre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lab_tyreCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lab_tyreCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 150, 160));

        jPanel6.setBackground(new java.awt.Color(19, 19, 19));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brakes Temperature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\brakes.png")); // NOI18N

        jPanel7.setBackground(new java.awt.Color(19, 19, 19));
        jPanel7.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        lab_brakeTempFL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_brakeTempFL.setForeground(new java.awt.Color(255, 255, 255));
        lab_brakeTempFL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_brakeTempFL.setText("jLabel2");
        jPanel7.add(lab_brakeTempFL);

        lab_brakeTempFR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_brakeTempFR.setForeground(new java.awt.Color(255, 255, 255));
        lab_brakeTempFR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_brakeTempFR.setText("jLabel2");
        jPanel7.add(lab_brakeTempFR);

        lab_brakeTempRL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_brakeTempRL.setForeground(new java.awt.Color(255, 255, 255));
        lab_brakeTempRL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_brakeTempRL.setText("jLabel2");
        jPanel7.add(lab_brakeTempRL);

        lab_brakeTempRR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_brakeTempRR.setForeground(new java.awt.Color(255, 255, 255));
        lab_brakeTempRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_brakeTempRR.setText("jLabel2");
        jPanel7.add(lab_brakeTempRR);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, 340, 110));

        jPanel8.setBackground(new java.awt.Color(19, 19, 19));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tyres Surface Temperature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\tyre_surface.png")); // NOI18N

        jPanel9.setBackground(new java.awt.Color(19, 19, 19));
        jPanel9.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        lab_tyreSurfaceTempFL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreSurfaceTempFL.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreSurfaceTempFL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreSurfaceTempFL.setText("jLabel2");
        jPanel9.add(lab_tyreSurfaceTempFL);

        lab_tyreSurfaceTempFR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreSurfaceTempFR.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreSurfaceTempFR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreSurfaceTempFR.setText("jLabel2");
        jPanel9.add(lab_tyreSurfaceTempFR);

        lab_tyreSurfaceTempRL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreSurfaceTempRL.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreSurfaceTempRL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreSurfaceTempRL.setText("jLabel2");
        jPanel9.add(lab_tyreSurfaceTempRL);

        lab_tyreSurfaceTempRR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreSurfaceTempRR.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreSurfaceTempRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreSurfaceTempRR.setText("jLabel2");
        jPanel9.add(lab_tyreSurfaceTempRR);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 340, 110));

        jPanel10.setBackground(new java.awt.Color(19, 19, 19));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tyres Inner Temperature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\tyre_inner.png")); // NOI18N

        jPanel11.setBackground(new java.awt.Color(19, 19, 19));
        jPanel11.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        lab_tyreInnerTempFL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreInnerTempFL.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreInnerTempFL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreInnerTempFL.setText("jLabel2");
        jPanel11.add(lab_tyreInnerTempFL);

        lab_tyreInnerTempFR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreInnerTempFR.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreInnerTempFR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreInnerTempFR.setText("jLabel2");
        jPanel11.add(lab_tyreInnerTempFR);

        lab_tyreInnerTempRL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreInnerTempRL.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreInnerTempRL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreInnerTempRL.setText("jLabel2");
        jPanel11.add(lab_tyreInnerTempRL);

        lab_tyreInnerTempRR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyreInnerTempRR.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreInnerTempRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreInnerTempRR.setText("jLabel2");
        jPanel11.add(lab_tyreInnerTempRR);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 240, -1, 110));

        jPanel12.setBackground(new java.awt.Color(19, 19, 19));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tyres Pressure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\tyre_pressure.png")); // NOI18N

        jPanel13.setBackground(new java.awt.Color(19, 19, 19));
        jPanel13.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        lab_tyrePressureFL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyrePressureFL.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyrePressureFL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyrePressureFL.setText("jLabel2");
        jPanel13.add(lab_tyrePressureFL);

        lab_tyrePressureFR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyrePressureFR.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyrePressureFR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyrePressureFR.setText("jLabel2");
        jPanel13.add(lab_tyrePressureFR);

        lab_tyrePressureRL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyrePressureRL.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyrePressureRL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyrePressureRL.setText("jLabel2");
        jPanel13.add(lab_tyrePressureRL);

        lab_tyrePressureRR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lab_tyrePressureRR.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyrePressureRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyrePressureRR.setText("jLabel2");
        jPanel13.add(lab_tyrePressureRR);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, -1, 110));

        panelPedals.setBackground(new java.awt.Color(19, 19, 19));
        panelPedals.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedals", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelPedals.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        pb_throttle.setBackground(new java.awt.Color(19, 19, 19));
        pb_throttle.setForeground(new java.awt.Color(0, 255, 0));
        pb_throttle.setOrientation(1);
        pb_throttle.setBorderPainted(false);
        panelPedals.add(pb_throttle);

        pb_brake.setBackground(new java.awt.Color(19, 19, 19));
        pb_brake.setForeground(new java.awt.Color(255, 102, 102));
        pb_brake.setOrientation(1);
        pb_brake.setBorderPainted(false);
        panelPedals.add(pb_brake);

        pb_clutch.setBackground(new java.awt.Color(19, 19, 19));
        pb_clutch.setForeground(new java.awt.Color(0, 102, 204));
        pb_clutch.setOrientation(1);
        pb_clutch.setBorderPainted(false);
        panelPedals.add(pb_clutch);

        jPanel4.add(panelPedals, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 570));

        lab_revs.setFont(new java.awt.Font("Formula1 Display Regular", 0, 12)); // NOI18N
        lab_revs.setForeground(new java.awt.Color(255, 255, 255));
        lab_revs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revs.setText("revs.");
        jPanel4.add(lab_revs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        panelSteer1.setBackground(new java.awt.Color(19, 19, 19));
        panelSteer1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revs (x1000)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelSteer1.setLayout(new java.awt.BorderLayout());

        panelSteerPercentage1.setBackground(new java.awt.Color(19, 19, 19));
        panelSteerPercentage1.setLayout(new javax.swing.BoxLayout(panelSteerPercentage1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setBackground(new java.awt.Color(19, 19, 19));
        jPanel14.setMinimumSize(new java.awt.Dimension(25, 50));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel14.setLayout(new java.awt.GridLayout(1, 15));

        lab_revLight1.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight1.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight1.setText("•");
        jPanel14.add(lab_revLight1);

        lab_revLight2.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight2.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight2.setText("•");
        jPanel14.add(lab_revLight2);

        lab_revLight3.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight3.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight3.setText("•");
        jPanel14.add(lab_revLight3);

        lab_revLight4.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight4.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight4.setText("•");
        jPanel14.add(lab_revLight4);

        lab_revLight5.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight5.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight5.setText("•");
        jPanel14.add(lab_revLight5);

        lab_revLight6.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight6.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight6.setText("•");
        jPanel14.add(lab_revLight6);

        lab_revLight7.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight7.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight7.setText("•");
        jPanel14.add(lab_revLight7);

        lab_revLight8.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight8.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight8.setText("•");
        jPanel14.add(lab_revLight8);

        lab_revLight9.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight9.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight9.setText("•");
        jPanel14.add(lab_revLight9);

        lab_revLight10.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight10.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight10.setText("•");
        jPanel14.add(lab_revLight10);

        lab_revLight11.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight11.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight11.setText("•");
        jPanel14.add(lab_revLight11);

        lab_revLight12.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight12.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight12.setText("•");
        jPanel14.add(lab_revLight12);

        lab_revLight13.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight13.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight13.setText("•");
        jPanel14.add(lab_revLight13);

        lab_revLight14.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight14.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight14.setText("•");
        jPanel14.add(lab_revLight14);

        lab_revLight15.setFont(new java.awt.Font("Calibri", 1, 78)); // NOI18N
        lab_revLight15.setForeground(new java.awt.Color(51, 51, 51));
        lab_revLight15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revLight15.setText("•");
        jPanel14.add(lab_revLight15);

        panelSteerPercentage1.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(19, 19, 19));
        jPanel15.setMaximumSize(new java.awt.Dimension(870, 15));
        jPanel15.setMinimumSize(new java.awt.Dimension(700, 15));
        jPanel15.setPreferredSize(new java.awt.Dimension(700, 15));
        jPanel15.setLayout(new java.awt.GridLayout(1, 5));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("3");
        jLabel2.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel15.add(jLabel2);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("6");
        jLabel12.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel15.add(jLabel12);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("9");
        jLabel13.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel15.add(jLabel13);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("12");
        jLabel14.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel15.add(jLabel14);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("15");
        jLabel15.setMaximumSize(new java.awt.Dimension(118, 14));
        jPanel15.add(jLabel15);

        panelSteerPercentage1.add(jPanel15);

        pb_revs.setBackground(new java.awt.Color(19, 19, 19));
        pb_revs.setForeground(new java.awt.Color(255, 255, 0));
        pb_revs.setMaximum(15000);
        pb_revs.setBorderPainted(false);
        pb_revs.setMaximumSize(new java.awt.Dimension(870, 14));
        panelSteerPercentage1.add(pb_revs);

        panelSteer1.add(panelSteerPercentage1, java.awt.BorderLayout.CENTER);

        jPanel4.add(panelSteer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 880, -1));

        panelSteer.setBackground(new java.awt.Color(19, 19, 19));
        panelSteer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Steer angle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelSteer.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("L");
        panelSteer.add(jLabel16, java.awt.BorderLayout.LINE_START);

        jLabel17.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("R");
        panelSteer.add(jLabel17, java.awt.BorderLayout.LINE_END);

        panelSteerPercentage.setBackground(new java.awt.Color(19, 19, 19));
        panelSteerPercentage.setLayout(new java.awt.GridLayout(1, 3));

        pb_steer_l.setBackground(new java.awt.Color(255, 255, 255));
        pb_steer_l.setForeground(new java.awt.Color(19, 19, 19));
        pb_steer_l.setValue(50);
        pb_steer_l.setBorderPainted(false);
        panelSteerPercentage.add(pb_steer_l);

        lab_steer.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_steer.setForeground(new java.awt.Color(255, 255, 255));
        lab_steer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_steer.setText("Steer %");
        panelSteerPercentage.add(lab_steer);

        pb_steer_r.setBackground(new java.awt.Color(19, 19, 19));
        pb_steer_r.setForeground(new java.awt.Color(255, 255, 255));
        pb_steer_r.setValue(50);
        panelSteerPercentage.add(pb_steer_r);

        panelSteer.add(panelSteerPercentage, java.awt.BorderLayout.CENTER);

        jPanel4.add(panelSteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 880, -1));

        combo_driver.setBackground(new java.awt.Color(153, 0, 0));
        combo_driver.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        combo_driver.setForeground(new java.awt.Color(255, 255, 255));

        lab_speed.setFont(new java.awt.Font("Formula1 Display Bold", 1, 36)); // NOI18N
        lab_speed.setForeground(new java.awt.Color(255, 255, 0));
        lab_speed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_speed.setText("SPEED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lab_flag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_driver, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_flag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(combo_driver)
                    .addComponent(lab_speed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        thread.controller.removePaso(thread.paso);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carDamageIcon;
    public javax.swing.JComboBox<String> combo_driver;
    private javax.swing.JLabel iconFuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lab_FLWD;
    public javax.swing.JLabel lab_FRWD;
    public javax.swing.JLabel lab_abs;
    public javax.swing.JLabel lab_brakeTempFL;
    public javax.swing.JLabel lab_brakeTempFR;
    public javax.swing.JLabel lab_brakeTempRL;
    public javax.swing.JLabel lab_brakeTempRR;
    public javax.swing.JLabel lab_drs;
    public javax.swing.JLabel lab_engine_damage;
    public javax.swing.JLabel lab_engine_temp;
    public javax.swing.JLabel lab_ersDeploy;
    public javax.swing.JLabel lab_ersModeNumber;
    public javax.swing.JLabel lab_ers_blue;
    public javax.swing.JLabel lab_ers_white;
    public javax.swing.JLabel lab_ers_yellow;
    public javax.swing.JLabel lab_exhaust_damage;
    public javax.swing.JLabel lab_flag;
    public javax.swing.JLabel lab_fuelExcess;
    public javax.swing.JLabel lab_fuelInTank;
    public javax.swing.JLabel lab_fuelMix;
    public javax.swing.JLabel lab_gear;
    public javax.swing.JLabel lab_gearbox_damage;
    public javax.swing.JLabel lab_pitLimiter;
    public javax.swing.JLabel lab_revLight1;
    public javax.swing.JLabel lab_revLight10;
    public javax.swing.JLabel lab_revLight11;
    public javax.swing.JLabel lab_revLight12;
    public javax.swing.JLabel lab_revLight13;
    public javax.swing.JLabel lab_revLight14;
    public javax.swing.JLabel lab_revLight15;
    public javax.swing.JLabel lab_revLight2;
    public javax.swing.JLabel lab_revLight3;
    public javax.swing.JLabel lab_revLight4;
    public javax.swing.JLabel lab_revLight5;
    public javax.swing.JLabel lab_revLight6;
    public javax.swing.JLabel lab_revLight7;
    public javax.swing.JLabel lab_revLight8;
    public javax.swing.JLabel lab_revLight9;
    public javax.swing.JLabel lab_revs;
    public javax.swing.JLabel lab_rwd;
    public javax.swing.JLabel lab_speed;
    public javax.swing.JLabel lab_steer;
    public javax.swing.JLabel lab_tyreCompound;
    public javax.swing.JLabel lab_tyreInnerTempFL;
    public javax.swing.JLabel lab_tyreInnerTempFR;
    public javax.swing.JLabel lab_tyreInnerTempRL;
    public javax.swing.JLabel lab_tyreInnerTempRR;
    public javax.swing.JLabel lab_tyrePressureFL;
    public javax.swing.JLabel lab_tyrePressureFR;
    public javax.swing.JLabel lab_tyrePressureRL;
    public javax.swing.JLabel lab_tyrePressureRR;
    public javax.swing.JLabel lab_tyreSurfaceTempFL;
    public javax.swing.JLabel lab_tyreSurfaceTempFR;
    public javax.swing.JLabel lab_tyreSurfaceTempRL;
    public javax.swing.JLabel lab_tyreSurfaceTempRR;
    private javax.swing.JPanel panelBars;
    private javax.swing.JPanel panelChecks;
    private javax.swing.JPanel panelERS;
    private javax.swing.JPanel panelFuelMix;
    private javax.swing.JPanel panelPedals;
    private javax.swing.JPanel panelPercentages;
    private javax.swing.JPanel panelSteer;
    private javax.swing.JPanel panelSteer1;
    private javax.swing.JPanel panelSteerPercentage;
    private javax.swing.JPanel panelSteerPercentage1;
    public javax.swing.JProgressBar pb_blue;
    public javax.swing.JProgressBar pb_brake;
    public javax.swing.JProgressBar pb_clutch;
    public javax.swing.JProgressBar pb_flwd;
    public javax.swing.JProgressBar pb_frwd;
    public javax.swing.JProgressBar pb_fuel;
    public javax.swing.JProgressBar pb_revs;
    public javax.swing.JProgressBar pb_rwd;
    public javax.swing.JProgressBar pb_steer_l;
    public javax.swing.JProgressBar pb_steer_r;
    public javax.swing.JProgressBar pb_throttle;
    public javax.swing.JProgressBar pb_tyreWearFL;
    public javax.swing.JProgressBar pb_tyreWearFR;
    public javax.swing.JProgressBar pb_tyreWearRL;
    public javax.swing.JProgressBar pb_tyreWearRR;
    public javax.swing.JProgressBar pb_white;
    public javax.swing.JProgressBar pb_yellow;
    // End of variables declaration//GEN-END:variables
}

class MyItemListener implements ItemListener {

    CarStatus_Thread thread;
    
    public MyItemListener(CarStatus_Thread t){
        thread = t;
    }
    
    public void itemStateChanged(ItemEvent evt) {
        JComboBox cb = (JComboBox) evt.getSource();

        String item = (String) evt.getItem();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            thread.setDriver(thread.controller.session.getDriverByName(item));
        }
    }
}