package gui.carstatus;

import classes.Controller;
import classes.statics.GUIFeatures;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author miguelangel.garciar
 */
public class CarStatus extends javax.swing.JFrame {

    CarStatus_Thread thread;
    
    public CarStatus(Controller controller) {
        initComponents();
        thread = new CarStatus_Thread(controller, this);
        thread.start();
        
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for(String p : controller.session.getAllNameParticipants()){
            dcbm.addElement(p);
        }
        combo_driver.setModel(dcbm);
        
        MyItemListener actionListener = new MyItemListener(thread);
        combo_driver.addItemListener(actionListener);
        combo_driver.setSelectedIndex(-1);
        
        GUIFeatures.setImageIcon(iconFuel, 40, 40, "icons/fuel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lab_flag = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelChecks = new javax.swing.JPanel();
        lab_pitLimiter = new javax.swing.JLabel();
        lab_drs = new javax.swing.JLabel();
        lab_abs = new javax.swing.JLabel();
        lab_gear = new javax.swing.JLabel();
        panelFuelMix = new javax.swing.JPanel();
        iconFuel = new javax.swing.JLabel();
        lab_fuelMix = new javax.swing.JLabel();
        panelERS = new javax.swing.JPanel();
        panelBars = new javax.swing.JPanel();
        pb_blue = new javax.swing.JProgressBar();
        pb_yellow = new javax.swing.JProgressBar();
        pb_white = new javax.swing.JProgressBar();
        panelPercentages = new javax.swing.JPanel();
        lab_ers_blue = new javax.swing.JLabel();
        lab_ers_yellow = new javax.swing.JLabel();
        lab_ers_white = new javax.swing.JLabel();
        lab_ersModeNumber = new javax.swing.JLabel();
        lab_ersDeploy = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        carDamageIcon = new javax.swing.JLabel();
        lab_tyreWearRR = new javax.swing.JLabel();
        pb_tyreWearRR = new javax.swing.JProgressBar();
        lab_tyreWearRL = new javax.swing.JLabel();
        pb_tyreWearRL = new javax.swing.JProgressBar();
        pb_tyreWearFR = new javax.swing.JProgressBar();
        lab_FRWD = new javax.swing.JLabel();
        pb_tyreWearFL = new javax.swing.JProgressBar();
        lab_tyreWearFL = new javax.swing.JLabel();
        pb_frwd = new javax.swing.JProgressBar();
        lab_tyreWearFR = new javax.swing.JLabel();
        pb_rwd = new javax.swing.JProgressBar();
        lab_rwd = new javax.swing.JLabel();
        pb_flwd = new javax.swing.JProgressBar();
        lab_FLWD = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lab_tyreCompound = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lab_engine_damage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lab_exhaust_damage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lab_gearbox_damage = new javax.swing.JLabel();
        combo_driver = new javax.swing.JComboBox<>();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Live Car Action");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        lab_flag.setBackground(new java.awt.Color(19, 19, 19));
        lab_flag.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_flag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_flag.setText("FLAG");
        lab_flag.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(19, 19, 19));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelChecks.setBackground(new java.awt.Color(19, 19, 19));
        panelChecks.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Console", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        panelChecks.setLayout(new java.awt.GridLayout(4, 1));

        lab_pitLimiter.setBackground(new java.awt.Color(0, 0, 0));
        lab_pitLimiter.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_pitLimiter.setForeground(new java.awt.Color(100, 100, 100));
        lab_pitLimiter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_pitLimiter.setText("PL");
        lab_pitLimiter.setOpaque(true);
        panelChecks.add(lab_pitLimiter);

        lab_drs.setBackground(new java.awt.Color(0, 0, 0));
        lab_drs.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_drs.setForeground(new java.awt.Color(255, 255, 255));
        lab_drs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_drs.setText("DRS");
        lab_drs.setOpaque(true);
        panelChecks.add(lab_drs);

        lab_abs.setBackground(new java.awt.Color(0, 0, 0));
        lab_abs.setFont(new java.awt.Font("Formula1 Display Bold", 0, 18)); // NOI18N
        lab_abs.setForeground(new java.awt.Color(255, 204, 51));
        lab_abs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_abs.setText("ABS");
        lab_abs.setOpaque(true);
        panelChecks.add(lab_abs);

        lab_gear.setFont(new java.awt.Font("Formula1 Display Bold", 0, 24)); // NOI18N
        lab_gear.setForeground(new java.awt.Color(153, 204, 255));
        lab_gear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_gear.setText("Gear");
        panelChecks.add(lab_gear);

        jPanel4.add(panelChecks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        panelFuelMix.setBackground(new java.awt.Color(19, 19, 19));
        panelFuelMix.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fuel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        iconFuel.setText("Fuel");

        lab_fuelMix.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_fuelMix.setForeground(new java.awt.Color(255, 153, 153));
        lab_fuelMix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fuelMix.setText("FuelMix");

        javax.swing.GroupLayout panelFuelMixLayout = new javax.swing.GroupLayout(panelFuelMix);
        panelFuelMix.setLayout(panelFuelMixLayout);
        panelFuelMixLayout.setHorizontalGroup(
            panelFuelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuelMixLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(iconFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_fuelMix, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelFuelMixLayout.setVerticalGroup(
            panelFuelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFuelMixLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelFuelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_fuelMix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.add(panelFuelMix, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        panelERS.setBackground(new java.awt.Color(19, 19, 19));
        panelERS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ERS Storage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        panelBars.setBackground(new java.awt.Color(19, 19, 19));
        panelBars.setForeground(new java.awt.Color(19, 19, 19));
        panelBars.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        pb_blue.setBackground(new java.awt.Color(51, 51, 51));
        pb_blue.setForeground(new java.awt.Color(0, 102, 255));
        pb_blue.setBorderPainted(false);
        panelBars.add(pb_blue);

        pb_yellow.setBackground(new java.awt.Color(51, 51, 51));
        pb_yellow.setForeground(new java.awt.Color(255, 204, 0));
        pb_yellow.setBorderPainted(false);
        panelBars.add(pb_yellow);

        pb_white.setBackground(new java.awt.Color(51, 51, 51));
        pb_white.setForeground(new java.awt.Color(255, 255, 255));
        pb_white.setBorderPainted(false);
        panelBars.add(pb_white);

        panelPercentages.setBackground(new java.awt.Color(19, 19, 19));
        panelPercentages.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        lab_ers_blue.setFont(new java.awt.Font("Formula1 Display Bold", 1, 18)); // NOI18N
        lab_ers_blue.setForeground(new java.awt.Color(0, 153, 204));
        lab_ers_blue.setText("Total");
        panelPercentages.add(lab_ers_blue);

        lab_ers_yellow.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lab_ers_yellow.setForeground(new java.awt.Color(255, 255, 0));
        lab_ers_yellow.setText("H+K");
        panelPercentages.add(lab_ers_yellow);

        lab_ers_white.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lab_ers_white.setForeground(new java.awt.Color(255, 255, 255));
        lab_ers_white.setText("Lap");
        panelPercentages.add(lab_ers_white);

        lab_ersModeNumber.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        lab_ersModeNumber.setForeground(new java.awt.Color(51, 153, 255));
        lab_ersModeNumber.setText("EL");

        lab_ersDeploy.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        lab_ersDeploy.setForeground(new java.awt.Color(51, 153, 255));
        lab_ersDeploy.setText("TBD");

        javax.swing.GroupLayout panelERSLayout = new javax.swing.GroupLayout(panelERS);
        panelERS.setLayout(panelERSLayout);
        panelERSLayout.setHorizontalGroup(
            panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelERSLayout.createSequentialGroup()
                .addComponent(panelBars, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPercentages, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelERSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_ersModeNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_ersDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelERSLayout.setVerticalGroup(
            panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelERSLayout.createSequentialGroup()
                .addGroup(panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPercentages, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelERSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_ersModeNumber)
                    .addComponent(lab_ersDeploy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(panelERS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(19, 19, 19));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Damage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carDamageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carDamageIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\miguelangel.garciar\\Documents\\NetBeansProjects\\F12018\\images\\icons\\car_damage.png")); // NOI18N
        jPanel3.add(carDamageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, 170));

        lab_tyreWearRR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearRR.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearRR.setText("RR");
        jPanel3.add(lab_tyreWearRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 50, 80));

        pb_tyreWearRR.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearRR.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearRR.setOrientation(1);
        pb_tyreWearRR.setBorderPainted(false);
        jPanel3.add(pb_tyreWearRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 15, 80));

        lab_tyreWearRL.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearRL.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearRL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearRL.setText("RL");
        jPanel3.add(lab_tyreWearRL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 80));

        pb_tyreWearRL.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearRL.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearRL.setOrientation(1);
        pb_tyreWearRL.setBorderPainted(false);
        jPanel3.add(pb_tyreWearRL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 15, 80));

        pb_tyreWearFR.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearFR.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearFR.setOrientation(1);
        pb_tyreWearFR.setBorderPainted(false);
        jPanel3.add(pb_tyreWearFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 15, 80));

        lab_FRWD.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_FRWD.setForeground(new java.awt.Color(153, 204, 255));
        lab_FRWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_FRWD.setText("FWR");
        lab_FRWD.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_FRWD.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_FRWD.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_FRWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 60, 20));

        pb_tyreWearFL.setBackground(new java.awt.Color(51, 51, 51));
        pb_tyreWearFL.setForeground(new java.awt.Color(255, 102, 102));
        pb_tyreWearFL.setOrientation(1);
        pb_tyreWearFL.setBorderPainted(false);
        jPanel3.add(pb_tyreWearFL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 15, 80));

        lab_tyreWearFL.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearFL.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearFL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearFL.setText("FL");
        jPanel3.add(lab_tyreWearFL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 80));

        pb_frwd.setBackground(new java.awt.Color(51, 51, 51));
        pb_frwd.setForeground(new java.awt.Color(0, 255, 0));
        pb_frwd.setValue(50);
        pb_frwd.setBorderPainted(false);
        jPanel3.add(pb_frwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 60, -1));

        lab_tyreWearFR.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_tyreWearFR.setForeground(new java.awt.Color(153, 204, 255));
        lab_tyreWearFR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreWearFR.setText("FR");
        lab_tyreWearFR.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_tyreWearFR.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_tyreWearFR.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_tyreWearFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 80));

        pb_rwd.setBackground(new java.awt.Color(51, 51, 51));
        pb_rwd.setForeground(new java.awt.Color(0, 255, 0));
        pb_rwd.setValue(50);
        pb_rwd.setBorderPainted(false);
        jPanel3.add(pb_rwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, -1));

        lab_rwd.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_rwd.setForeground(new java.awt.Color(153, 204, 255));
        lab_rwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_rwd.setText("RW");
        lab_rwd.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_rwd.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_rwd.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_rwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, 20));

        pb_flwd.setBackground(new java.awt.Color(51, 51, 51));
        pb_flwd.setForeground(new java.awt.Color(0, 255, 0));
        pb_flwd.setValue(50);
        pb_flwd.setBorderPainted(false);
        jPanel3.add(pb_flwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, -1));

        lab_FLWD.setFont(new java.awt.Font("Formula1 Display Regular", 0, 18)); // NOI18N
        lab_FLWD.setForeground(new java.awt.Color(153, 204, 255));
        lab_FLWD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_FLWD.setText("FWL");
        lab_FLWD.setMaximumSize(new java.awt.Dimension(50, 80));
        lab_FLWD.setMinimumSize(new java.awt.Dimension(50, 80));
        lab_FLWD.setPreferredSize(new java.awt.Dimension(50, 80));
        jPanel3.add(lab_FLWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 20));

        jPanel2.setBackground(new java.awt.Color(19, 19, 19));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compound", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        lab_tyreCompound.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        lab_tyreCompound.setForeground(new java.awt.Color(255, 255, 255));
        lab_tyreCompound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_tyreCompound.setText("Tyre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_tyreCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_tyreCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(19, 19, 19));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Engine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Engine");
        jPanel5.add(jLabel1);

        lab_engine_damage.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_engine_damage.setForeground(new java.awt.Color(255, 255, 0));
        lab_engine_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_engine_damage.setText("jLabel2");
        jPanel5.add(lab_engine_damage);

        jLabel3.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Exhaust");
        jPanel5.add(jLabel3);

        lab_exhaust_damage.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_exhaust_damage.setForeground(new java.awt.Color(255, 255, 0));
        lab_exhaust_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_exhaust_damage.setText("jLabel2");
        jPanel5.add(lab_exhaust_damage);

        jLabel7.setFont(new java.awt.Font("Formula1 Display Regular", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gear Box");
        jPanel5.add(jLabel7);

        lab_gearbox_damage.setFont(new java.awt.Font("Formula1 Display Regular", 1, 14)); // NOI18N
        lab_gearbox_damage.setForeground(new java.awt.Color(255, 255, 0));
        lab_gearbox_damage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_gearbox_damage.setText("jLabel2");
        jPanel5.add(lab_gearbox_damage);

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 270, 90));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 540, 320));

        combo_driver.setBackground(new java.awt.Color(153, 0, 0));
        combo_driver.setFont(new java.awt.Font("Formula1 Display Bold", 0, 14)); // NOI18N
        combo_driver.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_flag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_driver, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_flag, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(combo_driver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        thread.controller.removePaso(thread.paso);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carDamageIcon;
    public javax.swing.JComboBox<String> combo_driver;
    private javax.swing.JLabel iconFuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel lab_FLWD;
    public javax.swing.JLabel lab_FRWD;
    public javax.swing.JLabel lab_abs;
    public javax.swing.JLabel lab_drs;
    public javax.swing.JLabel lab_engine_damage;
    public javax.swing.JLabel lab_ersDeploy;
    public javax.swing.JLabel lab_ersModeNumber;
    public javax.swing.JLabel lab_ers_blue;
    public javax.swing.JLabel lab_ers_white;
    public javax.swing.JLabel lab_ers_yellow;
    public javax.swing.JLabel lab_exhaust_damage;
    public javax.swing.JLabel lab_flag;
    public javax.swing.JLabel lab_fuelMix;
    public javax.swing.JLabel lab_gear;
    public javax.swing.JLabel lab_gearbox_damage;
    public javax.swing.JLabel lab_pitLimiter;
    public javax.swing.JLabel lab_rwd;
    public javax.swing.JLabel lab_tyreCompound;
    public javax.swing.JLabel lab_tyreWearFL;
    public javax.swing.JLabel lab_tyreWearFR;
    public javax.swing.JLabel lab_tyreWearRL;
    public javax.swing.JLabel lab_tyreWearRR;
    private javax.swing.JPanel panelBars;
    private javax.swing.JPanel panelChecks;
    private javax.swing.JPanel panelERS;
    private javax.swing.JPanel panelFuelMix;
    private javax.swing.JPanel panelPercentages;
    public javax.swing.JProgressBar pb_blue;
    public javax.swing.JProgressBar pb_flwd;
    public javax.swing.JProgressBar pb_frwd;
    public javax.swing.JProgressBar pb_rwd;
    public javax.swing.JProgressBar pb_tyreWearFL;
    public javax.swing.JProgressBar pb_tyreWearFR;
    public javax.swing.JProgressBar pb_tyreWearRL;
    public javax.swing.JProgressBar pb_tyreWearRR;
    public javax.swing.JProgressBar pb_white;
    public javax.swing.JProgressBar pb_yellow;
    // End of variables declaration//GEN-END:variables
}

class MyItemListener implements ItemListener {

    CarStatus_Thread thread;
    
    public MyItemListener(CarStatus_Thread t){
        thread = t;
    }
    
    public void itemStateChanged(ItemEvent evt) {
        JComboBox cb = (JComboBox) evt.getSource();

        String item = (String) evt.getItem();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            thread.setDriver(thread.controller.session.getDriverByName(item));
        }
    }
}